project_name: kics

builds:
  - main: ./cmd/console/main.go
    binary: kics
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: darwin
        goarch: 386
      - goos: linux
        goarm: 7
      - goos: windows
        goarm: 7
    ldflags:
      - -s
      - -w
      - -X github.com/Checkmarx/kics/internal/constants.Version={{ .Version }}
      - -X github.com/Checkmarx/kics/internal/constants.SCMCommit={{ .Commit }}
